<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class RetsPropertyDataMul extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        //
        Schema::create('rets_property_data_mul', function (Blueprint $table) {
            $table->integer('id',11);
            $table->decimal('ACRES',9,2)->nullable();
            $table->string('ACRESTAX',144)->nullable()->default('NULL');
            $table->string('ADDRESSINCLUDED',144)->nullable()->default('NULL');
            $table->string('AGENTCOLIST',20)->nullable()->default('NULL');
            $table->string('AGENTCOSELL',20)->nullable()->default('NULL');
            $table->string('AGENTID',20)->nullable()->default('NULL');
            $table->string('AGENTOFFICEFEED',144)->nullable()->default('NULL');
            $table->string('AGENTSELL',20)->nullable()->default('NULL');
            $table->date('ANTICCLOSEDDATE');
            $table->string('ARIP',144)->nullable()->default('NULL');
            $table->integer('ASSESSAMOUNTBLDG')->nullable();
            $table->string('ASSESSAMOUNTBLDGTAX',144)->nullable()->default('NULL');
            $table->integer('ASSESSAMOUNTLAND')->nullable();
            $table->string('ASSESSAMOUNTLANDTAX',144)->nullable()->default('NULL');
            $table->text('ASSESSFARM')->nullable();
            $table->string('ASSESSTOTALTAX',144)->nullable()->default('NULL');
            $table->text('BASEDESC')->nullable();
            $table->string('BASEMENT',50)->nullable()->default('NULL');
            $table->integer('BATHSFULLTOTAL')->nullable();
            $table->integer('BATHSHALFTOTAL')->nullable();
            $table->integer('BATHSTOTAL')->nullable();
            $table->integer('BEDS')->nullable();
            $table->string('BLOCKID',10)->nullable()->default('NULL');
            $table->string('BLOCKIDTAX',144)->nullable()->default('NULL');
            $table->string('BUILDINGNUM',5)->nullable()->default('NULL');
            $table->text('BUSRELATION')->nullable();
            $table->string('CITY',26)->nullable()->default('NULL');
            $table->date('CLOSEDATE');
            $table->decimal('CLOSEPRICE',8,0)->nullable();
            $table->string('COLISTAGENTNAME',50)->nullable()->default('NULL');
            $table->string('COMPBUY',13)->nullable()->default('NULL');
            $table->string('COMPSELL',13)->nullable()->default('NULL');
            $table->string('COMPTRANS',13)->nullable()->default('NULL');
            $table->string('CONFIDENTIALINCLUDED',144)->nullable()->default('NULL');
            $table->date('CONTRACTDATE');
            $table->text('COOLING')->nullable();
            $table->string('COSELLAGENTNAME',50)->nullable()->default('NULL');
            $table->string('COUNTY',50)->nullable()->default('NULL');
            $table->string('COUNTYCODE',24)->nullable()->default('NULL');
            $table->string('COUNTYCODETAX',144)->nullable()->default('NULL');
            $table->string('COUNTYTAX',144)->nullable()->default('NULL');
            $table->integer('DAYSONMARKET')->nullable();
            $table->string('DIRECTIONS',100)->nullable()->default('NULL');
            $table->text('DISCLOSUREAVAIL')->nullable();
            $table->integer('DOMACT')->nullable();
            $table->integer('DOMCOMP')->nullable();
            $table->text('DRIVEWAYDESC')->nullable();
            $table->string('EASEDESC',13)->nullable()->default('NULL');
            $table->text('EASEMENT')->nullable();
            $table->string('ELEMENTARYSCHOOL',10)->nullable()->default('NULL');
            $table->string('EXCLUSIONS',71)->nullable()->default('NULL');
            $table->decimal('EXPENSEOPERATING',8,0)->nullable();
            $table->text('EXPENSES')->nullable();
            $table->date('EXPIRATIONDATE');
            $table->text('EXTERIOR')->nullable();
            $table->text('EXTERIORFEATURES')->nullable();
            $table->string('FHAAGERESTR',50)->nullable()->default('NULL');
            $table->date('FIRSTSHOWINGDATE');
            $table->decimal('GARAGE',2,0)->nullable();
            $table->text('GARAGEDESC')->nullable();
            $table->decimal('GROSSINCOME',8,0)->nullable();
            $table->text('HEATING')->nullable();
            $table->text('HEATSRC')->nullable();
            $table->string('HIGHSCHOOL',10)->nullable();
            $table->integer('IMAGECOUNT')->nullable();
            $table->datetime('IMAGEDATE');
            $table->text('INTERIORFEATURES')->nullable();
            $table->string('INTERNETAUTOMATEDVALUATIONDISPLAYYN',144)->nullable()->default('NULL');
            $table->string('INTERNETCONSUMERCOMMENTYN',144)->nullable()->default('NULL');
            $table->datetime('LASTMODIFIED');
            $table->decimal('LATITUDE',12,8)->nullable();
            $table->string('LENDERAPPROVAL',50)->nullable()->default('NULL');
            $table->string('LISTAGENTNAME',50)->nullable()->default('NULL');
            $table->string('LISTAGENTPHONE',16)->nullable()->default('NULL');
            $table->date('LISTDATE');
            $table->string('LISTINGID',38)->nullable()->default('NULL');
            $table->string('LISTINGSTATUS',50)->nullable()->default('NULL');
            $table->text('LISTINGTYPE')->nullable();
            $table->string('LISTOFFICEFAX',16)->nullable()->default('NULL');
            $table->string('LISTOFFICENAME',50)->nullable()->default('NULL');
            $table->string('LISTOFFICEPHONE',16)->nullable()->default('NULL');
            $table->decimal('LISTPRICE',8,0)->nullable();
            $table->string('LISTTYPERESO',50)->nullable()->default('NULL');
            $table->text('LOANTERMS')->nullable();
            $table->decimal('LONGITUDE',12,8)->nullable();
            $table->text('LOTDESC')->nullable();
            $table->string('LOTID',10)->nullable()->default('NULL');
            $table->string('LOTIDTAX',144)->nullable()->default('NULL');
            $table->string('LOTSIZE',25)->nullable()->default('NULL');
            $table->string('LOTSIZETAX',13)->nullable()->default('NULL');
            $table->decimal('LSTNGSYSID',15,0)->nullable();
            $table->datetime('MAJORCHANGETIMESTAMP');
            $table->string('MIDDLESCHOOL',10)->nullable()->default('NULL');
            $table->string('MLSTATUS',50)->nullable()->default('NULL');
            $table->decimal('NETINCOME',8,0)->nullable();
            $table->string('OFFICEID',20)->nullable()->default('NULL');
            $table->string('OFFICESELL',20)->nullable()->default('NULL');
            $table->decimal('OPENPARKING',3,0)->nullable();
            $table->datetime('ORIGINALENTRYDATETIME');
            $table->decimal('ORIGINALLISTPRICE',8,0)->nullable();
            $table->string('OUTOFCOUNTY',14)->nullable()->default('NULL');
            $table->string('OWNERNAMETAX',144)->nullable()->default('NULL');
            $table->string('OWNERPHONE',12)->nullable()->default('NULL');
            $table->string('OWNERSNAME',39)->nullable()->default('NULL');
            $table->text('PHOTOINSTR')->nullable();
            $table->string('POSSESSION',15)->nullable()->default('NULL');
            $table->text('POSSESSIONRESO')->nullable();
            $table->string('POSTALCODE',10)->nullable()->default('NULL');
            $table->string('PROPCOLOR',10)->nullable()->default('NULL');
            $table->text('PUBLICREMARKS')->nullable();
            $table->string('RCOMZIP',5)->nullable()->default('NULL');
            $table->string('REMARKS',100)->nullable()->default('NULL');
            $table->text('REMARKSPUBADD')->nullable();
            $table->integer('RENOVATED')->nullable();
            $table->string('REQUIREOFFICEINFO',144)->nullable()->default('NULL');
            $table->text('ROOF')->nullable();
            $table->integer('ROOMS')->nullable();
            $table->string('SELLAGENTNAME',50)->nullable()->default('NULL');
            $table->text('SERVICES')->nullable();
            $table->text('SEWER')->nullable();
            $table->text('SHOWINGINSTRUCTIONS')->nullable();
            $table->string('SHOWSPECIAL',68)->nullable()->default('NULL');
            $table->string('SIGN',50)->nullable()->default('NULL');
            $table->decimal('SQFTBLDG',6,0)->nullable();
            $table->string('STREETNAME',24)->nullable()->default('NULL');
            $table->string('STREETNAMETAX',144)->nullable()->default('NULL');
            $table->decimal('STREETNUMBER',9,0)->nullable();
            $table->string('STREETNUMDISPLAY',9)->nullable()->default('NULL');
            $table->string('STREETNUMTAX',144)->nullable()->default('NULL');
            $table->string('SUBDIVISION',20)->nullable()->default('NULL');
            $table->integer('TAXAMOUNT')->nullable();
            $table->string('TAXAMOUNTTAX',144)->nullable()->default('NULL');
            $table->integer('TAXASSESSEDVALUATION')->nullable();
            $table->string('TAXID',50)->nullable()->default('NULL');
            $table->string('TAXIDTAX',144)->nullable()->default('NULL');
            $table->decimal('TAXRATE',5,2)->nullable();
            $table->string('TAXRATETAX',144)->nullable()->default('NULL');
            $table->integer('TAXRATEYEAR')->nullable();
            $table->integer('TAXYEAR')->nullable();
            $table->string('TAXYEARTAX',144)->nullable()->default('NULL');
            $table->integer('TOTALUNITS')->nullable();
            $table->string('TOWNCODE',44)->nullable()->default('NULL');
            $table->string('TOWNCODETAX',144)->nullable()->default('NULL');
            $table->string('TOWNTAX',144)->nullable()->default('NULL');
            $table->text('UNIT1APPEQUIP')->nullable();
            $table->integer('UNIT1BATHS')->nullable();
            $table->integer('UNIT1BEDS')->nullable();
            $table->decimal('UNIT1FIREPLACES',2,0)->nullable();
            $table->string('UNIT1HANDICAP',50)->nullable()->default('NULL');
            $table->date('UNIT1LEASEEXPIRE');
            $table->decimal('UNIT1LEVELS',1,0)->nullable();
            $table->text('UNIT1OWNERTENANTPAYS')->nullable();
            $table->decimal('UNIT1RENT',4,0)->nullable();
            $table->text('UNIT1ROOMDESC')->nullable();
            $table->decimal('UNIT1ROOMS',3,0)->nullable();
            $table->decimal('UNIT1SECDEP',10,0)->nullable();
            $table->decimal('UNIT1SQFT',4,0)->nullable();
            $table->string('UNIT1TENANTNAME',25)->nullable()->default('NULL');
            $table->string('UNIT1TENANTPHONE',25)->nullable()->default('NULL');
            $table->text('UNIT2APPEQUIP')->nullable();
            $table->integer('UNIT2BATHS')->nullable();
            $table->integer('UNIT2BEDS')->nullable();
            $table->decimal('UNIT2FIREPLACES',2,0)->nullable();
            $table->string('UNIT2HANDICAP',50)->nullable()->default('NULL');
            $table->date('UNIT2LEASEEXPIRE');
            $table->decimal('UNIT2LEVELS',1,0)->nullable();
            $table->text('UNIT2OWNERTENANTPAYS')->nullable();
            $table->decimal('UNIT2RENT',4,0)->nullable();
            $table->text('UNIT2ROOMDESC')->nullable();
            $table->decimal('UNIT2ROOMS',3,0)->nullable();
            $table->decimal('UNIT2SECDEP',10,0)->nullable();
            $table->decimal('UNIT2SQFT',4,0)->nullable();
            $table->string('UNIT2TENANTNAME',25)->nullable()->default('NULL');
            $table->string('UNIT2TENANTPHONE',25)->nullable()->default('NULL');
            $table->text('UNIT3APPEQUIP')->nullable();
            $table->integer('UNIT3BATHS')->nullable();
            $table->integer('UNIT3BEDS')->nullable();
            $table->decimal('UNIT3FIREPLACES',2,0)->nullable();
            $table->string('UNIT3HANDICAP',50)->nullable()->default('NULL');
            $table->date('UNIT3LEASEEXPIRE');
            $table->decimal('UNIT3LEVELS',1,0)->nullable();
            $table->text('UNIT3OWNERTENANTPAYS')->nullable();
            $table->decimal('UNIT3RENT',4,0)->nullable();
            $table->text('UNIT3ROOMDESC')->nullable();
            $table->decimal('UNIT3ROOMS',2,0)->nullable();
            $table->decimal('UNIT3SECDEP',10,0)->nullable();
            $table->decimal('UNIT3SQFT',4,0)->nullable();
            $table->string('UNIT3TENANTNAME',25)->nullable()->default('NULL');
            $table->string('UNIT3TENANTPHONE',25)->nullable()->default('NULL');
            $table->text('UNIT4APPEQUIP')->nullable();
            $table->integer('UNIT4BATHS')->nullable();
            $table->integer('UNIT4BEDS')->nullable();
            $table->decimal('UNIT4FIREPLACES',2,0)->nullable();
            $table->string('UNIT4HANDICAP',50)->nullable()->default('NULL');
            $table->date('UNIT4LEASEEXPIRE');
            $table->decimal('UNIT4LEVELS',1,0)->nullable();
            $table->text('UNIT4OWNERTENANTPAYS')->nullable();
            $table->decimal('UNIT4RENT',4,0)->nullable();
            $table->text('UNIT4ROOMDESC')->nullable();
            $table->decimal('UNIT4ROOMS',2,0)->nullable();
            $table->decimal('UNIT4SECDEP',10,0)->nullable();
            $table->decimal('UNIT4SQFT',4,0)->nullable();
            $table->string('UNIT4TENANTNAME',25)->nullable()->default('NULL');
            $table->string('UNIT4TENANTPHONE',25)->nullable()->default('NULL');
            $table->string('UNITNUMBER',44)->nullable()->default('NULL');
            $table->text('UNITSTYLE')->nullable();
            $table->text('UTILITIES')->nullable();
            $table->string('WARRANTY',50)->nullable()->default('NULL');
            $table->text('WATER')->nullable();
            $table->text('WATERHEATER')->nullable();
            $table->date('WITHDRAWNDATE');
            $table->integer('YEARBUILT')->nullable();
            $table->text('YEARBUILTDESC')->nullable();
            $table->string('ZIPCODETAX',144)->nullable()->default('NULL');
            $table->string('ZONING',13)->nullable()->default('NULL');
            $table->integer('IMAGEDOWNLOADED');
            $table->integer('IMAGEDOWNLOADEDTRIED')->nullable();
            $table->string('IMAGEDOWNLOADEDTIME')->nullable()->default('NULL');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
        Schema::dropIfExists('rets_property_data_mul');
    }
}
