<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class RetsPropertyDataComm extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        //
        Schema::create('rets_property_data_comm', function (Blueprint $table) {
            $table->integer('id',11);
            $table->decimal('ACRES',9,2)->nullable();
            $table->string('ACRESTAX',144)->nullable()->default('NULL');
            $table->string('ADDRESSINCLUDED',14)->nullable()->default('NULL');
            $table->string('AGENTCOLIST',20)->nullable()->default('NULL');
            $table->string('AGENTCOSELL',20)->nullable()->default('NULL');
            $table->string('AGENTID',20)->nullable()->default('NULL');
            $table->string('AGENTOFFICEFEED',144)->nullable()->default('NULL');
            $table->string('AGENTSELL',20)->nullable()->default('NULL');
            $table->date('ANTICCLOSEDDATE');
            $table->string('ARIP',144)->nullable()->default('NULL');
            $table->integer('ASSESSAMOUNTBLDG')->nullable();
            $table->string('ASSESSAMOUNTBLDGTAX')->nullable()->default('NULL');
            $table->integer('ASSESSAMOUNTLAND')->nullable();
            $table->string('ASSESSAMOUNTLANDTAX',144)->nullable()->default('NULL');
            $table->text('ASSESSFARM')->nullable();
            $table->string('ASSESSTOTALTAX',144)->nullable()->default('NULL');
            $table->text('AVAILABLE')->nullable();
            $table->text('BASEDESC')->nullable();
            $table->string('BASEMENT',50)->nullable()->default('NULL');
            $table->string('BLOCKID',10)->nullable()->default('NULL');
            $table->string('BLOCKIDTAX',144)->nullable()->default('NULL');
            $table->string('BUILDINGNUM',5)->nullable()->default('NULL');
            $table->text('BUSRELATION')->nullable();
            $table->string('CAM',8)->nullable()->default('NULL');
            $table->decimal('CAPRATE',5,2)->nullable();
            $table->decimal('CEILHIMAX',6,0)->nullable();
            $table->string('CITY',26)->nullable()->default('NULL');
            $table->date('CLOSEDATE');
            $table->decimal('CLOSEPRICE',8,0)->nullable();
            $table->string('COLISTAGENTNAME',50)->nullable()->default('NULL');
            $table->decimal('COLUMNSPACE',5,0)->nullable();
            $table->string('COMPBUY',13)->nullable()->default('NULL');
            $table->string('COMPSELL',13)->nullable()->default('NULL');
            $table->string('COMPTRANS',13)->nullable()->default('NULL');
            $table->string('CONFIDENTIALINCLUDED',144)->nullable()->default('NULL');
            $table->text('CONSTRUCTION')->nullable();
            $table->date('CONTRACTDATE');
            $table->text('COOLING')->nullable();
            $table->string('COSELLAGENTNAME',50)->nullable()->default('NULL');
            $table->string('COUNTY',50)->nullable()->default('NULL');
            $table->string('COUNTYCODE',24)->nullable()->default('NULL');
            $table->string('COUNTYCODETAX',144)->nullable()->default('NULL');
            $table->string('COUNTYTAX',144)->nullable()->default('NULL');
            $table->integer('DAYSONMARKET')->nullable();
            $table->text('DEPSTATUS')->nullable();
            $table->string('DIRECTIONS',100)->nullable()->default('NULL');
            $table->text('DISCLOSUREAVAIL')->nullable();
            $table->text('DOCSAVAIL')->nullable();
            $table->integer('DOMACT')->nullable();
            $table->decimal('DOORHIMAX',5,0)->nullable();
            $table->string('EASEDESC',13)->nullable()->default('NULL');
            $table->text('EASEMENT')->nullable();
            $table->text('EQUIPAVAIL')->nullable();
            $table->decimal('EXPENSEOPERATING',8,0)->nullable();
            $table->text('EXPENSES')->nullable();
            $table->date('EXPIRATIONDATE');
            $table->text('EXTERIOR')->nullable();
            $table->date('FIRSTSHOWINGDATE');
            $table->decimal('FLOORLOAD',5,0)->nullable();
            $table->text('FLOORS')->nullable();
            $table->string('FORSALEORLEASE',50)->nullable()->default('NULL');
            $table->string('FREERENT',50)->nullable()->default('NULL');
            $table->decimal('GARAGE',2,0)->nullable();
            $table->string('GARAGEDESC',26)->nullable()->default('NULL');
            $table->decimal('GROSSINCOME',8,0)->nullable();
            $table->text('HEATING')->nullable();
            $table->text('HEATSRC')->nullable();
            $table->integer('IMAGECOUNT')->nullable();
            $table->datetime('IMAGEDATE');
            $table->string('INTERNETAUTOMATEDVALUATIONDISPLAYYN',144)->nullable()->default('NULL');
            $table->string('INTERNETCONSUMERCOMMENTYN',144)->nullable()->default('NULL');
            $table->string('LANDLORDSWORK',15)->nullable()->default('NULL');
            $table->datetime('LASTMODIFIED');
            $table->decimal('LATITUDE',12,8)->nullable();
            $table->text('LEASEINCLUDES')->nullable();
            $table->text('LEASEINFO')->nullable();
            $table->string('LEASETYPE',50)->nullable()->default('NULL');
            $table->string('LENDERAPPROVAL',50)->nullable()->default('NULL');
            $table->string('LISTAGENTNAME',50)->nullable()->default('NULL');
            $table->string('LISTAGENTPHONE',16)->nullable()->default('NULL');
            $table->date('LISTDATE');
            $table->string('LISTINGID',38)->nullable()->default('NULL');
            $table->string('LISTINGSTATUS',50)->nullable()->default('NULL');
            $table->text('LISTINGTYPE')->nullable();
            $table->string('LISTOFFICEFAX',16)->nullable()->default('NULL');
            $table->string('LISTOFFICENAME',50)->nullable()->default('NULL');
            $table->string('LISTOFFICEPHONE',16)->nullable()->default('NULL');
            $table->decimal('LISTPRICE',8,0)->nullable();
            $table->string('LISTTYPERESO',50)->nullable()->default('NULL');
            $table->text('LOADINGINFO')->nullable();
            $table->text('LOANTERMS')->nullable();
            $table->text('LOCATION')->nullable();
            $table->decimal('LONGITUDE',12,8)->nullable();
            $table->text('LOTDESC')->nullable();
            $table->string('LOTID',10)->nullable()->default('NULL');
            $table->string('LOTIDTAX',144)->nullable()->default('NULL');
            $table->string('LOTSIZE',25)->nullable()->default('NULL');
            $table->string('LOTSIZETAX',144)->nullable()->default('NULL');
            $table->decimal('LSTNGSYSID',15,0)->nullable();
            $table->decimal('MAINTFEE',8,0)->nullable();
            $table->datetime('MAJORCHANGETIMESTAMP');
            $table->string('MLSTATUS',50)->nullable()->default('NULL');
            $table->decimal('NETINCOME',8,0)->nullable();
            $table->decimal('NUM1BEDUNITS',5,0)->nullable();
            $table->decimal('NUM2BEDUNITS',5,0)->nullable();
            $table->decimal('NUM3BEDUNITS',5,0)->nullable();
            $table->decimal('NUM4BEDUNITS',5,0)->nullable();
            $table->string('NUMAMPS',6)->nullable()->default('NULL');
            $table->decimal('NUMAPTS',5,0)->nullable();
            $table->decimal('NUMBAYS',4,0)->nullable();
            $table->decimal('NUMDOCKS',5,0)->nullable();
            $table->decimal('NUMDOORS',5,0)->nullable();
            $table->integer('NUMLAVS')->nullable();
            $table->decimal('NUMUNITSFBATH',5,0)->nullable();
            $table->decimal('NUMUNITSHBATH',5,0)->nullable();
            $table->string('NUMVOLTS',6)->nullable()->default('NULL');
            $table->date('OCCUPDATE');
            $table->string('OFFICEID',20)->nullable()->default('NULL');
            $table->string('OFFICESELL',20)->nullable()->default('NULL');
            $table->datetime('ORIGINALENTRYDATETIME');
            $table->decimal('ORIGINALLISTPRICE',8,0)->nullable();
            $table->string('OUTOFCOUNTY',14)->nullable()->default('NULL');
            $table->string('OWNERNAMETAX',144)->nullable()->default('NULL');
            $table->text('OWNERPAYS')->nullable();
            $table->string('OWNERPHONE',12)->nullable()->default('NULL');
            $table->string('OWNERSHIPTYPE',50)->nullable()->default('NULL');
            $table->string('OWNERSNAME',39)->nullable()->default('NULL');
            $table->decimal('PARKAVAIL',4,0)->nullable();
            $table->text('PARKINGDESC')->nullable();
            $table->string('PERMITTEDUSE',50)->nullable()->default('NULL');
            $table->text('PHOTOINSTR')->nullable();
            $table->string('POSSESSION',15)->nullable()->default('NULL');
            $table->text('POSSESSIONRESO')->nullable();
            $table->string('POSTALCODE',10)->nullable()->default('NULL');
            $table->string('PRERENTALREQ',100)->nullable()->default('NULL');
            $table->string('PRIORUSE',50)->nullable()->default('NULL');
            $table->string('PROPCOLOR',10)->nullable()->default('NULL');
            $table->text('PROPERTYTYPE')->nullable();
            $table->string('PROPERTYTYPEPRIMARY',50)->nullable()->default('NULL');
            $table->text('PUBLICREMARKS')->nullable();
            $table->string('RCOMZIP',5)->nullable()->default('NULL');
            $table->string('REMARKS',100)->nullable()->default('NULL');
            $table->text('REMARKSPUBADD')->nullable();
            $table->integer('RENOVATED')->nullable();
            $table->string('REPORTDETAILS')->nullable()->default('NULL');
            $table->string('REQUIREOFFICEINFO',144)->nullable()->default('NULL');
            $table->text('ROOF')->nullable();
            $table->text('SALEINCLUDES')->nullable();
            $table->string('SELLAGENTNAME',50)->nullable()->default('NULL');
            $table->text('SERVICES')->nullable();
            $table->text('SEWER')->nullable();
            $table->text('SHOWINGINSTRUCTIONS')->nullable();
            $table->string('SHOWSPECIAL',68)->nullable()->default('NULL');
            $table->string('SIGN',50)->nullable()->default('NULL');
            $table->decimal('SQFTAVAIL',6,0)->nullable();
            $table->decimal('SQFTBLDG',6,0)->nullable();
            $table->decimal('SQFTOFFICE',6,0)->nullable();
            $table->decimal('SQFTPRICE',6,2)->nullable();
            $table->decimal('SQFTSALEPRICE',6,2)->nullable();
            $table->integer('STORIES')->nullable();
            $table->string('STREETNAME',24)->nullable()->default('NULL');
            $table->string('STREETNAMETAX',144)->nullable()->default('NULL');
            $table->decimal('STREETNUMBER',9,0)->nullable();
            $table->string('STREETNUMDISPLAY',9)->nullable()->default('NULL');
            $table->string('STREETNUMTAX',144)->nullable()->default('NULL');
            $table->string('SUBDIVISION',20)->nullable()->default('NULL');
            $table->string('SUITENUM',5)->nullable()->default('NULL');
            $table->integer('TAXAMOUNT')->nullable();
            $table->string('TAXAMOUNTTAX',144)->nullable()->default('NULL');
            $table->integer('TAXASSESSEDVALUATION')->nullable();
            $table->string('TAXID',50)->nullable()->default('NULL');
            $table->string('TAXIDTAX',144)->nullable()->default('NULL');
            $table->decimal('TAXRATE',5,2)->nullable();
            $table->string('TAXRATETAX',144)->nullable()->default('NULL');
            $table->integer('TAXRATEYEAR')->nullable();
            $table->integer('TAXYEAR')->nullable();
            $table->string('TAXYEARTAX',144)->nullable()->default('NULL');
            $table->string('TENANTLANDLORDPAYS',50)->nullable()->default('NULL');
            $table->text('TENANTPAYS')->nullable();
            $table->integer('TOTALUNITS')->nullable();
            $table->string('TOWNCODE',4)->nullable()->default('NULL');
            $table->string('TOWNCODETAX',144)->nullable()->default('NULL');
            $table->string('TOWNTAX',144)->nullable()->default('NULL');
            $table->text('UTILITIES')->nullable();
            $table->text('UTILPAIDBY')->nullable();
            $table->text('WATER')->nullable();
            $table->date('WITHDRAWNDATE');
            $table->integer('YEARBUILT')->nullable();
            $table->text('YEARBUILTDESC')->nullable();
            $table->string('ZIPCODETAX',144)->nullable()->default('NULL');
            $table->string('ZONING',13)->nullable()->default('NULL');
            $table->string('ZONINGCOMP',50)->nullable()->default('NULL');
            $table->integer('IMAGEDOWNLOADED')->default('0');
            $table->integer('IMAGEDOWNLOADEDTRIED')->nullable();
            $table->string('IMAGEDOWNLOADEDTIME')->nullable()->default('NULL');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
        Schema::dropIfExists('rets_property_data_comm');
    }
}
