<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class RetsPropertyDataBus extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        //
        Schema::create('rets_property_data_bus', function (Blueprint $table) {
            $table->integer('id',11);
            $table->text('ACCEPTFINANCE')->nullable();
            $table->string('ADDRESSINCLUDED')->nullable()->default('NULL');
            $table->string('AGENTCOLIST',20)->nullable()->default('NULL');
            $table->string('AGENTCOSELL',20)->nullable()->default('NULL');
            $table->string('AGENTID',20)->nullable()->default('NULL');
            $table->string('AGENTOFFICEFEED')->nullable()->default('NULL');
            $table->string('AGENTSELL',20)->nullable()->default('NULL');
            $table->date('ANTICCLOSEDDATE');
            $table->string('ARIP')->nullable()->default('NULL');
            $table->text('BASEDESC')->nullable();
            $table->string('BASEMENT',50)->nullable()->default('NULL');
            $table->string('BUILDINGNUM',5)->nullable()->default('NULL');
            $table->text('BUSCLASS')->nullable();
            $table->string('BUSCLASSPRIMARY',50)->nullable()->default('NULL');
            $table->integer('BUSESTABLISHED')->nullable();
            $table->string('BUSINESSNAME',20)->nullable()->default('NULL');
            $table->text('BUSRELATION')->nullable();
            $table->string('CITY',26)->nullable()->default('NULL');
            $table->date('CLOSEDATE');
            $table->decimal('CLOSEPRICE',8,0)->nullable();
            $table->string('COLISTAGENTNAME',50)->nullable()->default('NULL');
            $table->string('COMPBUY',13)->nullable()->default('NULL');
            $table->string('COMPSELL',13)->nullable()->default('NULL');
            $table->string('COMPTRANS',13)->nullable()->default('NULL');
            $table->string('CONFIDENTIALINCLUDED')->nullable()->default('NULL');
            $table->date('CONTRACTDATE');
            $table->text('COOLING')->nullable();
            $table->string('COSELLAGENTNAME',50)->nullable()->default('NULL');
            $table->string('COUNTY',50)->nullable()->default('NULL');
            $table->string('COUNTYCODE',255)->nullable()->default('NULL');
            $table->string('COUNTYCODETAX',155)->nullable()->default('NULL');
            $table->string('COUNTYTAX',155)->nullable()->default('NULL');
            $table->integer('DAYSONMARKET')->nullable();
            $table->string('DIRECTIONS',100)->nullable()->default('NULL');
            $table->text('DISCLOSUREAVAIL')->nullable();
            $table->text('DOCSAVAIL')->nullable();
            $table->integer('DOMACT')->nullable();
            $table->text('DRIVEWAYDESC')->nullable();
            $table->text('EXISTINGLEASE')->nullable();
            $table->decimal('EXPENSEOPERATING',8,0)->nullable();
            $table->date('EXPIRATIONDATE');
            $table->date('FIRSTSHOWINGDATE');
            $table->text('GARAGEDESC')->nullable();
            $table->decimal('GROSSINCOME',8,0)->nullable();
            $table->text('HEATING')->nullable();
            $table->text('HEATSRC')->nullable();
            $table->string('HOURSOFOPERATION',45)->nullable()->default('NULL');
            $table->integer('IMAGECOUNT')->nullable();
            $table->datetime('IMAGEDATE');
            $table->text('INCEXPSOURCE')->nullable();
            $table->string('INTERNETAUTOMATEDVALUATIONDISPLAYYN',155)->nullable()->default('NULL');
            $table->string('INTERNETCONSUMERCOMMENTYN',155)->nullable()->default('NULL');
            $table->datetime('LASTMODIFIED');
            $table->decimal('LATITUDE',12,8)->nullable();
            $table->date('LEASEEXPIREDATE');
            $table->decimal('LEASEMONTHLY',8,0)->nullable();
            $table->string('LENDERAPPROVAL',50)->nullable()->default('NULL');
            $table->string('LISTAGENTNAME',50)->nullable()->default('NULL');
            $table->string('LISTAGENTPHONE',16)->nullable()->default('NULL');
            $table->date('LISTDATE');
            $table->string('LISTINGID',38)->nullable()->default('NULL');
            $table->string('LISTINGSTATUS',50)->nullable()->default('NULL');
            $table->text('LISTINGTYPE')->nullable();
            $table->string('LISTOFFICEFAX',16)->nullable()->default('NULL');
            $table->string('LISTOFFICENAME',50)->nullable()->default('NULL');
            $table->string('LISTOFFICEPHONE',16)->nullable()->default('NULL');
            $table->decimal('LISTPRICE',8,0)->nullable();
            $table->string('LISTTYPERESO',50)->nullable()->default('NULL');
            $table->text('LOANTERMS')->nullable();
            $table->text('LOCATION')->nullable();
            $table->decimal('LONGITUDE',12,8)->nullable();
            $table->decimal('LSTNGSYSID',15,0)->nullable();
            $table->datetime('MAJORCHANGETIMESTAMP');
            $table->string('MLSTATUS',50)->nullable()->default('NULL');
            $table->decimal('NETINCOME',8,0)->nullable();
            $table->decimal('NUMEMPLOY',5,0)->nullable();
            $table->integer('NUMLAVS')->nullable();
            $table->string('OFFICEID',20)->nullable()->default('NULL');
            $table->string('OFFICESELL',20)->nullable()->default('NULL');
            $table->datetime('ORIGINALENTRYDATETIME');
            $table->decimal('ORIGINALLISTPRICE',8,0)->nullable();
            $table->string('OUTOFCOUNTY',14)->nullable()->default('NULL');
            $table->string('OWNERNAMETAX',155)->nullable()->default('NULL');
            $table->string('OWNERPHONE',12)->nullable()->default('NULL');
            $table->string('OWNERSHIPTYPE',50)->nullable()->default('NULL');
            $table->string('OWNERSNAME',39)->nullable()->default('NULL');
            $table->text('PHOTOINSTR')->nullable();
            $table->string('POSSESSION',15)->nullable()->default('NULL');
            $table->text('POSSESSIONRESO')->nullable();
            $table->string('POSTALCODE',10)->nullable()->default('NULL');
            $table->text('PRICEINCLUDES')->nullable();
            $table->text('PUBLICREMARKS')->nullable();
            $table->string('RCOMZIP',5)->nullable()->default('NULL');
            $table->text('REASONFORSALE')->nullable();
            $table->text('REFORSALE')->nullable();
            $table->string('REMARKS',100)->nullable()->default('NULL');
            $table->text('REMARKSPUBADD')->nullable();
            $table->string('REPORTDETAILS')->nullable()->default('NULL');
            $table->string('REQUIREOFFICEINFO',155)->nullable()->default('NULL');
            $table->text('ROADTYPE')->nullable();
            $table->string('SELLAGENTNAME',50)->nullable()->default('NULL');
            $table->text('SERVICES')->nullable();
            $table->text('SEWER')->nullable();
            $table->text('SHOWINGINSTRUCTIONS')->nullable();
            $table->string('SHOWSPECIAL',68)->nullable()->default('NULL');
            $table->string('SIGN',50)->nullable()->default('NULL');
            $table->decimal('SQFTAVAIL',6,0)->nullable();
            $table->decimal('SQFTTOTAL',6,0)->nullable();
            $table->string('STREETNAME',24)->nullable()->default('NULL');
            $table->string('STREETNAMETAX',144)->nullable()->default('NULL');
            $table->decimal('STREETNUMBER',9,0)->nullable();
            $table->string('STREETNUMDISPLAY',9)->nullable()->default('NULL');
            $table->string('STREETNUMTAX',144)->nullable()->default('NULL');
            $table->string('SUBDIVISION',20)->nullable()->default('NULL');
            $table->string('TAXID',50)->nullable()->default('NULL');
            $table->string('TAXIDTAX',144)->nullable()->default('NULL');
            $table->string('TOWNCODE',4)->nullable()->default('NULL');
            $table->string('TOWNCODETAX',144)->nullable()->default('NULL');
            $table->string('TOWNTAX',144)->nullable()->default('NULL');
            $table->decimal('UTILAMOUNT',8,0)->nullable();
            $table->text('UTILITIES')->nullable();
            $table->text('WATER')->nullable();
            $table->date('WITHDRAWNDATE');
            $table->string('ZIPCODETAX',144)->nullable()->default('NULL');
            $table->string('ZONING',13)->nullable()->default('NULL');
            $table->integer('IMAGEDOWNLOADED')->default('0');
            $table->integer('IMAGEDOWNLOADEDTRIED')->nullable();
            $table->string('IMAGEDOWNLOADEDTIME')->nullable()->default('NULL');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
        Schema::dropIfExists('rets_property_data_bus');
    }
}
